### ISSUE TITLE
[Feature request] send from image browser to outpaint

### ISSUE THREAD

**Issue by Rogal80** [zero01101/openOutpaint-webUI-extension#2]
Hi, awesome extension :), is there any chance to add button in the image browser – that we can send directly to outpaint

**Comment by seijihariki** [comment]
Image browser... You say the extension?

**Comment by seijihariki** [comment]
Image browser... You mean the extension?

**Comment by Rogal80** [comment]
yes :)

**Comment by seijihariki** [comment]
@zero01101 do you know if there is any inter-extension support on the webui? If there is nothing we will probably have to JavaScript our way into the extension...

**Comment by zero01101** [comment]
:/ can't say that i do unfortunately; from what i've poked around with in webUI's codebase i didn't see anything that'd accommodate that (certainly doesn't mean it's not _there_ however) nor did it seem like any of the extensions i have installed do anything like that... wonder how that'd work via JS though, like what happens if openOutpaint is initialized before the image browser?

**Comment by seijihariki** [comment]
We can deal with that in JavaScript, no issue. But I think it would be hard to get generation info in that case. Sending the image would be quite okay I imagine.

**Comment by seijihariki** [comment]
For now, we have a send image from image browser to openoutpaint button. Still, generation configuration is not an option for now.

@Rogal80 can you give this a look? You need to enter the extension folder (`/extensions/openOutpaint-webUI-extension`) and run `git checkout testing` and `git pull`.

Then you go to the webui extensions tab and click on 'Apply and restart UI'.

**Comment by seijihariki** [comment]
@Rogal80 This is now in main, so just need to update the extension and it should work.

**Comment by Rogal80** [comment]
thx :)
