### ISSUE TITLE
Refresh button always shown; covers up parts of the UI

### ISSUE THREAD

**Issue by Baughn** [zero01101/openOutpaint-webUI-extension#4]
See image...

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/45811/209385651-3d65c03a-075d-409f-bb9a-bbec50d10f63.png">

This is on Chrome, OSX. My best guess is that this shouldn't be there.

**Comment by Mousewrites** [comment]
Yup, same, chrome on windows 10, button is the width of the window.

**Comment by zero01101** [comment]
>My best guess is that this shouldn't be there.

your best guess is spot on lol, sorry about that - pushed a quick fix to handle that, should be able to pull the latest update from A1111 webUI extensions page :)

i'm not closing this yet because it's a hacky "max-width" pixel value and i think that's kind of less than best practice, but it at least makes the extension less broken :D

**Comment by seijihariki** [comment]
It is definitely way bigger than it should be. Will fix this as soon as I can.

**Comment by Mousewrites** [comment]
Great extention so far, been waiting for something like this to help with outpaining in auto1111

**Comment by seijihariki** [comment]
@zero01101 in this case `width: fit-content` should work better.
