### ISSUE TITLE
[Bug]: Index.html does not exist / {"detail":"File not found"}

### ISSUE THREAD

**Issue by OO-ooo-OO** [zero01101/openOutpaint-webUI-extension#52]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

Index.html does not exist

### Steps to reproduce the problem

Index.html does not exist

### What should have happened?

Should exist

### Commit where the problem happens

n/a

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

N/A

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --no-half --medvram --api

**Comment by zero01101** [comment]
hey, sorry for the delay; is there anything reported in your console logs/f12 browser devtools?  obviously that's not how the extension should install and isn't reproducible so it sounds a lot like it's a local issue...

**Comment by zero01101** [comment]
terribly sorry for the extended delay; this project isn't abandoned but i've had to step away from it due to Reasons for a while, and i admit additional responses may (aka will probably) be delayed but hopefully not nearly as long

gotcha, so you installed the extension manually via a zip bundle?  it's probably infinitely easier to just use the extensions page but that should still work... however it sounds like you're not getting the submodule which is actually the entirety of openOutpaint, and i'm guessing there's some local restriction or foible preventing you from doing so, ergo the zip

i'm also going to guess there's no `app` folder in the openOutpaint extension's folder?  if that's the case you can try downloading a similar zip archive of [openOutpaint](https://github.com/zero01101/openOutpaint) and extracting the contents to a folder titled `app` within the `openOutpaint-webUI-extension` folder
