### ISSUE TITLE
Add the scripts tab to the UI 

### ISSUE THREAD

**Issue by brehiner** [zero01101/openOutpaint-webUI-extension#55]
### Is your feature request related to a problem? Please describe.

I'm generating images with the script Vector Studio but when I want to extend the generated image in Open Out Paint can see that all new images generate are not similar artistic style.

### Describe the solution you'd like

Add the script dropdown menu in the UI of Open Out Paint, and make that work the script choosen in my case Vector Studio.

### Proposed workflow

1. Go to the UI of Open Out Paint 
2. Press the dropdown menu of scripts
3. choose your script

### Describe alternatives you've considered

Automaticly recognize the script choosen in the UI or automatic1111 without no need to add the dropdown menu

**Comment by zero01101** [comment]
terribly sorry for the extended delay; this project isn't abandoned but i've had to step away from it due to Reasons for a while, and i admit additional responses may (aka will probably) be delayed but hopefully not nearly as long

actually, what you seek kinda already exists; check the [manual](https://github.com/zero01101/openOutpaint/wiki/Manual#script) ;) it takes some manual elbow grease to get working, ergo it's experimental and hidden away
